#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#ifndef LOG_BACKEND_USB_ENABLED
#define LOG_BACKEND_USB_ENABLED 1
#endif

#ifndef LOG_BACKEND_USB_TMP_BUFFER_SIZE
#define LOG_BACKEND_USB_TMP_BUFFER_SIZE 64
#endif

#ifndef LOG_BACKEND_USB_CDC_ACM_COMM_INTERFACE
#define LOG_BACKEND_USB_CDC_ACM_COMM_INTERFACE 0
#endif

#ifndef LOG_BACKEND_USB_CDC_ACM_DATA_INTERFACE
#define LOG_BACKEND_USB_CDC_ACM_DATA_INTERFACE 1
#endif

#ifndef LOG_BACKEND_USB_CDC_ACM_COMM_EPIN
#define LOG_BACKEND_USB_CDC_ACM_COMM_EPIN NRF_DRV_USBD_EPIN2
#endif

#ifndef LOG_BACKEND_USB_CDC_ACM_DATA_EPIN
#define LOG_BACKEND_USB_CDC_ACM_DATA_EPIN NRF_DRV_USBD_EPIN1
#endif

#ifndef LOG_BACKEND_USB_CDC_ACM_DATA_EPOUT
#define LOG_BACKEND_USB_CDC_ACM_DATA_EPOUT NRF_DRV_USBD_EPOUT1
#endif

#ifndef LOG_BACKEND_USB_INIT_STACK
#define LOG_BACKEND_USB_INIT_STACK 1
#endif

#ifndef LOG_BACKEND_USB_UTILIZE_POWER_EVENTS
#define LOG_BACKEND_USB_UTILIZE_POWER_EVENTS 1
#endif

#ifndef CDC_ACM_COMM_INTERFACE
#define CDC_ACM_COMM_INTERFACE 2
#endif

#ifndef CDC_ACM_DATA_INTERFACE
#define CDC_ACM_DATA_INTERFACE 3
#endif

#ifndef CDC_ACM_COMM_EPIN
#define CDC_ACM_COMM_EPIN NRF_DRV_USBD_EPIN3
#endif

#ifndef CDC_ACM_DATA_EPIN
#define CDC_ACM_DATA_EPIN NRF_DRV_USBD_EPIN4
#endif

#ifndef CDC_ACM_DATA_EPOUT
#define CDC_ACM_DATA_EPOUT NRF_DRV_USBD_EPOUT4
#endif

#ifndef APP_TIMER_V2
#define APP_TIMER_V2
#endif

#ifndef APP_TIMER_V2_RTC1_ENABLED
#define APP_TIMER_V2_RTC1_ENABLED
#endif

#ifndef NRFX_NVMC_ENABLED
#define NRFX_NVMC_ENABLED 1
#endif

#endif
